language: java
sudo: false
install: true
jdk:
  - openjdk8
  - openjdk11
script:
  - mvn -q clean package
after_success:
  - mvn -q sonar:sonar
addons:
  sonarcloud:
    organization: "erudika"
    token:
      secure: "o7cgrKj7ihwRlYw3QZOQgO9CYw/1e54zLwvi3jIXwN2ex7dPUSNwpr6t5xBNXb3InQJgnibqFT7Kzqv5kzj1ZMBS9fRK1/6yrNAWc04wNCYPO4D+JbYGgNHbUCllUfce0J03Ee3+yKdQCp9k2lbFJlM4cVnaRuPUk88fK+DqWn4="
cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04820972e9b664f3140c
    on_success: change
    on_failure: always
    on_start: never